### ISSUE TITLE
Not Working in Android 

### ISSUE THREAD

**Issue by AndroVirus** [SaherBlueEagle/XPR-2020-Free#1]
hi bro
i am trying your RAT, 
In Emulator Victim Show, but install in phone Victim not show, netstat show connection established.
plz help me

**Comment by SaherBlueEagle** [comment]
> netstat show connectio
i think the google protect on real updated phones prevent the connection , even if turned off . because when i tested it on emulator with old version it worked perfect , but on androids which higher than android "API Level 14" it didn`t succeed , and keeps connecting but prevented to transmit data , that was reported to me also , as this issue fixed in the HTTP XPR , but it`s not released yet , i tested it on my phone to , but a Hint : try to crypt the apk / as some do with "njRAT" trojans , you can crypt also that apk / or changing it`s certificate / or something like that to prevent it from being detected and making it FUD apk trojan and will work and control phone as was in the video

**Comment by SaherBlueEagle** [comment]
Dear AndroVirus  ;
Kindly check the update of the mentioned bug above , and re-check the new version that receives connections , [Apk Bug Fixed] 
Thanks for your support and attention ;)

**Comment by AndroVirus** [comment]
What is Password of RAR file

**Comment by SaherBlueEagle** [comment]
please read the Rar comment tips carefully you will find the password inside it "XPR_2020_Free" and please read the comment points carefully for 100% perfect usage of the tool

**Comment by AndroVirus** [comment]
Thanks

**Comment by SaherBlueEagle** [comment]
U all r Welcome , Any Time ; Thank you for your support , and attention , any bug also you can report it in new issue to allow others to get informed ;) 
Thank You ;
Best Regards

**Comment by AndroVirus** [comment]
Sure Bro i make a post on my site using your RAT and give your github link

**Comment by SaherBlueEagle** [comment]
Thank You Bro. ❤️ for your support

**Comment by jewishscientist1** [comment]
Any crypter recommendation for the apk stub ?

**Comment by SaherBlueEagle** [comment]
this may be others mission is to program a crypter or do a method for crypting apk stubs

**Comment by jewishscientist1** [comment]
When I try to take a picture on remote client See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at BlueEagleXPR.Android_cam.Button2_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4220.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
BlueEagleXPR
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/AD02/Downloads/XPR-2020-Free-master/XPR_Offensive%20Version2020%20Update2/BlueEagleXPR.exe
----------------------------------------
ShutdownMode.AfterMainFormCloses + Char.GetNumericValue
    Assembly Version: 0.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/AD02/Downloads/XPR-2020-Free-master/XPR_Offensive%20Version2020%20Update2/BlueEagleXPR.exe
----------------------------------------
Microsoft.VisualBasic
    Assembly Version: 10.0.0.0
    Win32 Version: 14.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4200.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4200.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4220.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
System.Runtime.Remoting
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Remoting/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Remoting.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by SaherBlueEagle** [comment]
this may be a rare fault inside the windows machine , but unfortunately this error didn`t appear to me , thus i couldn`t know a way to solve this , just it worked perfect on the machines i have tested on :(

**Comment by jewishscientist1** [comment]
Okay I am running it on  a windows 10 virtual machine. Do you mind sharing what version of windows you are running it on ?

**Comment by jewishscientist1** [comment]
Bro, why is it that on the phone I tested the sms messages do not show in full ? It shows half way. Say something like this. Dear value customer, Thank y.......... the rest of the message doesn't show. Is that normal ? Also I don't seem to be able to get key logs from the client. Is everything functioning normal for you ?

**Comment by SaherBlueEagle** [comment]
> ng functioning
to enable keylogger to get keylogs , go to accessibility features inside client android and turn on that feature for the client apk 
and sms works fine to me , but this may happen due to difference in android version only for the client
